services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "monika"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "moniela8116"
      - key: GENERIC_TIMEZONE
        value: "Asia/Kolkata"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com"   # replace with your Render URL
